#!/bin/bash

chmod 774 crux-test.pl
ln -fs test.fasta existing.fasta

./crux-test.pl -p ../ crux-test.cmds 1>out 2>error
if [ $? == 25 ]
then echo "Test aborted"
else
	tail -n6 out
fi

echo "  Test output in the file 'out'.  Error messages in 'error'."
