#!/bin/bash

chmod 774 crux-test.pl
ln -fs test.fasta existing.fasta
if [ ! -e index-for-sequest-comparison ]
then ../crux create-index  --parameter-file params/mods-sequest --verbosity 0 for-sequest-comparison.fasta index-for-sequest-comparison
fi

# remove any lingering output files
./clean.sh

./crux-test.pl -p ../ crux-test.cmds 1>out 2>error
if [ $? == 25 ]
then echo "Test aborted"
else
	tail -n6 out
fi

echo "  Test output in the file 'out'.  Error messages in 'error'."
