#include "Params.h"
#include "parameter.h"

using namespace std;

void Params::InitDIAmeterOptions() {
  // added by Yang
  /* DIAmeter-related options */
  InitStringParam("predrt-files", "",
    "The name of file from which to parse the predicted retention time of each peptide in the database. "
    "The file is tab-delimited where the first column is peptide and the second column is the predicted rt information. "
    "The rt prediction doesn't require normalization beforehand. "
    "If the peptide in the database is missing in the prediction, its predicted value will be imputed by the median of all predicted values.",
    "It is optional but recommended for DIAmeter. It can be easily generated by DeepRT or any off-the-shelf "
    "RT prediction tools by feeding in the peptide-list generated by tide-index", true);

  InitIntParam("msamanda-regional-topk", 10, 1, 1000000,
    "Analogous to the peak-picking in MS Amanda, the m/z range is divided into 10 equal length segments, "
    "and in each segment, the k most intense peaks are preserved.",
    "It is used for DIAmeter", true);

  InitIntParam("coelution-oneside-scans", 3, 1, 100,
    "(2*coelution-oneside-scans+1) scans will be used to construct the chromatogram for coelution correlation analysis",
    "It is used for DIAmeter", true);

  InitIntParam("coelution-topk", 1, 1, 10,
    "The number of topk values to consider to calculate precursor fragment co-elution",
    "It is used for DIAmeter", true);

  InitDoubleParam("coeff-precursor", 1.0, 0, 100,
    "The coefficient to balance the precursor intensity rank feature in calculating the aggregated score",
    "It is used for DIAmeter", false);

  InitDoubleParam("coeff-fragment", 1.0, 0, 100,
    "The coefficient to balance the fragment matching p-value feature in calculating the aggregated score",
    "It is used for DIAmeter", false);

  InitDoubleParam("coeff-rtdiff", 1.0, 0, 100,
    "The coefficient to balance the retention time difference feature in calculating the aggregated score",
    "It is used for DIAmeter", false);

  InitDoubleParam("coeff-elution", 1.0, 0, 100,
    "The coefficient to balance the precursor and fragment co-elution feature in calculating the aggregated score",
    "It is used for DIAmeter", false);

  InitStringParam("coeff-tag", "",
    "The tag to encode the information about coefficients",
    "It is optional but recommended for DIAmeter. If not provided, DIAmeter will automatically generate on combining all coefficients.", false);

  InitIntParam("prec-ppm", 10, 1, 1000000,
    "Tolerance used for matching precursors to spectra. "
    "Peptides must be within +/- ‘precursor-ppm’ parts-per-million (ppm) of the spectrum precursor m/z",
    "It is used for DIAmeter. Default = 10 (orbitrap) and =30 (triptof)", true);

  InitIntParam("frag-ppm", 10, 1, 1000000,
    "Tolerance used for matching fragment ions to spectrum peaks. "
    "Fragment ions must be within +/- 'fragment-ppm' of the spectrum peak value.",
    "It is used for DIAmeter. Default = 10 (orbitrap) and =30 (triptof)", true);

  InitBoolParam("unique-scannr", false,
    "Make the ScanNr of each PSM unique in the .pin file.",
    "It is used for make-pin", true);

  InitBoolParam("psm-filter", false,
    "Filter the PSM by the ensemble score.",
    "It is used for DIAmeter", true);

  InitBoolParam("spectra-denoising", false,
      "Eliminate MS2 peak if neither of the adjacent scans contains the same peak within a specified tolerance.",
      "It is used for DIAmeter", true);

  InitStringParam("diameter-instrument", "na", "orbitrap|tof5600|tof6600|na",
    "Specify the instrument platform used to acquire the input spectra. "
    "This option selects among different sets of coefficient values for the scores computed by diameter. "
    "Specifically, the 'orbitrap' setting is equivalent to spectra-denoising=false, psm-filter=false, prec-ppm=10,frag-ppm=10; "
    "the 'tof5600' is equivalent to spectra-denoising=true, psm-filter=true, prec-ppm=30, frag-ppm=30, coeff-precursor=3.2, coeff-fragment=0.2, coeff-rtdiff=0.2, coeff-elution=0.2; "
    "the 'tof6600' is equivalent to spectra-denoising=false, psm-filter=true, prec-ppm=30, frag-ppm=30, coeff-precursor=25.6, coeff-fragment=0.2, coeff-rtdiff=0.2, coeff-elution=0. "
    "Use diameter-instrument=na to set individual parameters.  Otherwise, parameters set using diameter-instrument will override any parameters set separately. ",
    "It is used for DIAmeter", true);

}
