/**
 * 
 */
package edu.washington.gs.noble.crux.gui;

import java.awt.Component;
import java.awt.Dimension;
import java.util.logging.Logger;

import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 * The FeatureFilePanel class is the GUI elements used to get and set the 
 * whether a feature file is generated by percolator or q-ranker
 *
 * @author Charles E. Grant
 *
 */public class FeatureFilePanel extends CruxAdvancedParameterControl {
	 
		private static Logger logger = 
			Logger.getLogger("edu.washington.gs.noble.crux.gui");

		private final CruxGui cruxGui;
		private final JPanel panel = new JPanel();
		private final JCheckBox featureFileCheckBox = new JCheckBox("Enable feature file");

		public FeatureFilePanel(CruxGui cruxGui) {
			this.cruxGui = cruxGui;
			setLayout(new BoxLayout(this, BoxLayout.Y_AXIS));
			setAlignmentX(Component.LEFT_ALIGNMENT);
			panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));
			panel.add(featureFileCheckBox);
			add(panel);
			updateFromModel();
		}	
		
		public void loadDefaults() {
			CruxAnalysisModel model = cruxGui.getAnalysisModel();
			featureFileCheckBox.setSelected(model.getFeatureFileDefault());
		}
		
		public void saveToModel() {
			CruxAnalysisModel model = cruxGui.getAnalysisModel();
			model.setUseFeatureFile(getFeatureFile());
			logger.info("Saved parameter 'feature-file' to model: " + getFeatureFile());
		}
		
		private boolean getFeatureFile() {
			return featureFileCheckBox.isSelected();
		}

		public void updateFromModel() {
			CruxAnalysisModel model = cruxGui.getAnalysisModel();
			featureFileCheckBox.setSelected(model.useFeatureFile());
			logger.info("Loaded parameter 'feature-file' from model: " + model.useFeatureFile());
		}
}
