// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: indexed_mass_spectral_peak.proto

#include "indexed_mass_spectral_peak.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace crux_lfq {
constexpr Ms1ScanInfo::Ms1ScanInfo(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : one_based_scan_number_(0)
  , zero_based_ms1_scan_index_(0)
  , retention_time_(0){}
struct Ms1ScanInfoDefaultTypeInternal {
  constexpr Ms1ScanInfoDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Ms1ScanInfoDefaultTypeInternal() {}
  union {
    Ms1ScanInfo _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Ms1ScanInfoDefaultTypeInternal _Ms1ScanInfo_default_instance_;
constexpr IndexedMassSpectralPeak::IndexedMassSpectralPeak(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : mz_(0)
  , intensity_(0)
  , retention_time_(0)
  , zero_based_ms1_scan_index_(0){}
struct IndexedMassSpectralPeakDefaultTypeInternal {
  constexpr IndexedMassSpectralPeakDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~IndexedMassSpectralPeakDefaultTypeInternal() {}
  union {
    IndexedMassSpectralPeak _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT IndexedMassSpectralPeakDefaultTypeInternal _IndexedMassSpectralPeak_default_instance_;
constexpr InnerMap_InnerMapEntry_DoNotUse::InnerMap_InnerMapEntry_DoNotUse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct InnerMap_InnerMapEntry_DoNotUseDefaultTypeInternal {
  constexpr InnerMap_InnerMapEntry_DoNotUseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~InnerMap_InnerMapEntry_DoNotUseDefaultTypeInternal() {}
  union {
    InnerMap_InnerMapEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT InnerMap_InnerMapEntry_DoNotUseDefaultTypeInternal _InnerMap_InnerMapEntry_DoNotUse_default_instance_;
constexpr InnerMap::InnerMap(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : inner_map_(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}){}
struct InnerMapDefaultTypeInternal {
  constexpr InnerMapDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~InnerMapDefaultTypeInternal() {}
  union {
    InnerMap _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT InnerMapDefaultTypeInternal _InnerMap_default_instance_;
constexpr Ms1ScanInfoList::Ms1ScanInfoList(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : ms1_scan_info_(){}
struct Ms1ScanInfoListDefaultTypeInternal {
  constexpr Ms1ScanInfoListDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~Ms1ScanInfoListDefaultTypeInternal() {}
  union {
    Ms1ScanInfoList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT Ms1ScanInfoListDefaultTypeInternal _Ms1ScanInfoList_default_instance_;
constexpr IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct IndexedSpectralResults_IndexedPeaksEntry_DoNotUseDefaultTypeInternal {
  constexpr IndexedSpectralResults_IndexedPeaksEntry_DoNotUseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~IndexedSpectralResults_IndexedPeaksEntry_DoNotUseDefaultTypeInternal() {}
  union {
    IndexedSpectralResults_IndexedPeaksEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT IndexedSpectralResults_IndexedPeaksEntry_DoNotUseDefaultTypeInternal _IndexedSpectralResults_IndexedPeaksEntry_DoNotUse_default_instance_;
constexpr IndexedSpectralResults_Ms1ScansEntry_DoNotUse::IndexedSpectralResults_Ms1ScansEntry_DoNotUse(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized){}
struct IndexedSpectralResults_Ms1ScansEntry_DoNotUseDefaultTypeInternal {
  constexpr IndexedSpectralResults_Ms1ScansEntry_DoNotUseDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~IndexedSpectralResults_Ms1ScansEntry_DoNotUseDefaultTypeInternal() {}
  union {
    IndexedSpectralResults_Ms1ScansEntry_DoNotUse _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT IndexedSpectralResults_Ms1ScansEntry_DoNotUseDefaultTypeInternal _IndexedSpectralResults_Ms1ScansEntry_DoNotUse_default_instance_;
constexpr IndexedSpectralResults::IndexedSpectralResults(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : indexed_peaks_(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{})
  , ms1_scans_(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}){}
struct IndexedSpectralResultsDefaultTypeInternal {
  constexpr IndexedSpectralResultsDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~IndexedSpectralResultsDefaultTypeInternal() {}
  union {
    IndexedSpectralResults _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT IndexedSpectralResultsDefaultTypeInternal _IndexedSpectralResults_default_instance_;
}  // namespace crux_lfq
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[8];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_indexed_5fmass_5fspectral_5fpeak_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_indexed_5fmass_5fspectral_5fpeak_2eproto = nullptr;

const uint32_t TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::crux_lfq::Ms1ScanInfo, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::Ms1ScanInfo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::Ms1ScanInfo, one_based_scan_number_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::Ms1ScanInfo, zero_based_ms1_scan_index_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::Ms1ScanInfo, retention_time_),
  0,
  1,
  2,
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedMassSpectralPeak, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedMassSpectralPeak, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedMassSpectralPeak, mz_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedMassSpectralPeak, intensity_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedMassSpectralPeak, zero_based_ms1_scan_index_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedMassSpectralPeak, retention_time_),
  0,
  1,
  3,
  2,
  PROTOBUF_FIELD_OFFSET(::crux_lfq::InnerMap_InnerMapEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::InnerMap_InnerMapEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::InnerMap_InnerMapEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::InnerMap_InnerMapEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::InnerMap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::InnerMap, inner_map_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::Ms1ScanInfoList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::Ms1ScanInfoList, ms1_scan_info_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse, value_),
  0,
  1,
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse, _has_bits_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse, key_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults, indexed_peaks_),
  PROTOBUF_FIELD_OFFSET(::crux_lfq::IndexedSpectralResults, ms1_scans_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 9, -1, sizeof(::crux_lfq::Ms1ScanInfo)},
  { 12, 22, -1, sizeof(::crux_lfq::IndexedMassSpectralPeak)},
  { 26, 34, -1, sizeof(::crux_lfq::InnerMap_InnerMapEntry_DoNotUse)},
  { 36, -1, -1, sizeof(::crux_lfq::InnerMap)},
  { 43, -1, -1, sizeof(::crux_lfq::Ms1ScanInfoList)},
  { 50, 58, -1, sizeof(::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse)},
  { 60, 68, -1, sizeof(::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse)},
  { 70, -1, -1, sizeof(::crux_lfq::IndexedSpectralResults)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_Ms1ScanInfo_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_IndexedMassSpectralPeak_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_InnerMap_InnerMapEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_InnerMap_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_Ms1ScanInfoList_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_IndexedSpectralResults_IndexedPeaksEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_IndexedSpectralResults_Ms1ScansEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::crux_lfq::_IndexedSpectralResults_default_instance_),
};

const char descriptor_table_protodef_indexed_5fmass_5fspectral_5fpeak_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n indexed_mass_spectral_peak.proto\022\010crux"
  "_lfq\"g\n\013Ms1ScanInfo\022\035\n\025one_based_scan_nu"
  "mber\030\001 \002(\005\022!\n\031zero_based_ms1_scan_index\030"
  "\002 \002(\005\022\026\n\016retention_time\030\003 \002(\001\"s\n\027Indexed"
  "MassSpectralPeak\022\n\n\002mz\030\001 \002(\001\022\021\n\tintensit"
  "y\030\002 \002(\001\022!\n\031zero_based_ms1_scan_index\030\003 \002"
  "(\005\022\026\n\016retention_time\030\004 \002(\001\"\223\001\n\010InnerMap\022"
  "3\n\tinner_map\030\001 \003(\0132 .crux_lfq.InnerMap.I"
  "nnerMapEntry\032R\n\rInnerMapEntry\022\013\n\003key\030\001 \001"
  "(\005\0220\n\005value\030\002 \001(\0132!.crux_lfq.IndexedMass"
  "SpectralPeak:\0028\001\"\?\n\017Ms1ScanInfoList\022,\n\rm"
  "s1_scan_info\030\001 \003(\0132\025.crux_lfq.Ms1ScanInf"
  "o\"\273\002\n\026IndexedSpectralResults\022I\n\rindexed_"
  "peaks\030\001 \003(\01322.crux_lfq.IndexedSpectralRe"
  "sults.IndexedPeaksEntry\022A\n\tms1_scans\030\002 \003"
  "(\0132..crux_lfq.IndexedSpectralResults.Ms1"
  "ScansEntry\032G\n\021IndexedPeaksEntry\022\013\n\003key\030\001"
  " \001(\005\022!\n\005value\030\002 \001(\0132\022.crux_lfq.InnerMap:"
  "\0028\001\032J\n\rMs1ScansEntry\022\013\n\003key\030\001 \001(\t\022(\n\005val"
  "ue\030\002 \001(\0132\031.crux_lfq.Ms1ScanInfoList:\0028\001B"
  "\002H\001"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto = {
  false, false, 803, descriptor_table_protodef_indexed_5fmass_5fspectral_5fpeak_2eproto, "indexed_mass_spectral_peak.proto", 
  &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once, nullptr, 0, 8,
  schemas, file_default_instances, TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto::offsets,
  file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto, file_level_enum_descriptors_indexed_5fmass_5fspectral_5fpeak_2eproto, file_level_service_descriptors_indexed_5fmass_5fspectral_5fpeak_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter() {
  return &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_indexed_5fmass_5fspectral_5fpeak_2eproto(&descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto);
namespace crux_lfq {

// ===================================================================

class Ms1ScanInfo::_Internal {
 public:
  using HasBits = decltype(std::declval<Ms1ScanInfo>()._has_bits_);
  static void set_has_one_based_scan_number(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_zero_based_ms1_scan_index(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_retention_time(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x00000007) ^ 0x00000007) != 0;
  }
};

Ms1ScanInfo::Ms1ScanInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:crux_lfq.Ms1ScanInfo)
}
Ms1ScanInfo::Ms1ScanInfo(const Ms1ScanInfo& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&one_based_scan_number_, &from.one_based_scan_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&retention_time_) -
    reinterpret_cast<char*>(&one_based_scan_number_)) + sizeof(retention_time_));
  // @@protoc_insertion_point(copy_constructor:crux_lfq.Ms1ScanInfo)
}

inline void Ms1ScanInfo::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&one_based_scan_number_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&retention_time_) -
    reinterpret_cast<char*>(&one_based_scan_number_)) + sizeof(retention_time_));
}

Ms1ScanInfo::~Ms1ScanInfo() {
  // @@protoc_insertion_point(destructor:crux_lfq.Ms1ScanInfo)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Ms1ScanInfo::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Ms1ScanInfo::ArenaDtor(void* object) {
  Ms1ScanInfo* _this = reinterpret_cast< Ms1ScanInfo* >(object);
  (void)_this;
}
void Ms1ScanInfo::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Ms1ScanInfo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Ms1ScanInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:crux_lfq.Ms1ScanInfo)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    ::memset(&one_based_scan_number_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&retention_time_) -
        reinterpret_cast<char*>(&one_based_scan_number_)) + sizeof(retention_time_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Ms1ScanInfo::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required int32 one_based_scan_number = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _Internal::set_has_one_based_scan_number(&has_bits);
          one_based_scan_number_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required int32 zero_based_ms1_scan_index = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 16)) {
          _Internal::set_has_zero_based_ms1_scan_index(&has_bits);
          zero_based_ms1_scan_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required double retention_time = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 25)) {
          _Internal::set_has_retention_time(&has_bits);
          retention_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ms1ScanInfo::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:crux_lfq.Ms1ScanInfo)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required int32 one_based_scan_number = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(1, this->_internal_one_based_scan_number(), target);
  }

  // required int32 zero_based_ms1_scan_index = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(2, this->_internal_zero_based_ms1_scan_index(), target);
  }

  // required double retention_time = 3;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(3, this->_internal_retention_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:crux_lfq.Ms1ScanInfo)
  return target;
}

size_t Ms1ScanInfo::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:crux_lfq.Ms1ScanInfo)
  size_t total_size = 0;

  if (_internal_has_one_based_scan_number()) {
    // required int32 one_based_scan_number = 1;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_one_based_scan_number());
  }

  if (_internal_has_zero_based_ms1_scan_index()) {
    // required int32 zero_based_ms1_scan_index = 2;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_zero_based_ms1_scan_index());
  }

  if (_internal_has_retention_time()) {
    // required double retention_time = 3;
    total_size += 1 + 8;
  }

  return total_size;
}
size_t Ms1ScanInfo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:crux_lfq.Ms1ScanInfo)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x00000007) ^ 0x00000007) == 0) {  // All required fields are present.
    // required int32 one_based_scan_number = 1;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_one_based_scan_number());

    // required int32 zero_based_ms1_scan_index = 2;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_zero_based_ms1_scan_index());

    // required double retention_time = 3;
    total_size += 1 + 8;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Ms1ScanInfo::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Ms1ScanInfo::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Ms1ScanInfo::GetClassData() const { return &_class_data_; }

void Ms1ScanInfo::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Ms1ScanInfo *>(to)->MergeFrom(
      static_cast<const Ms1ScanInfo &>(from));
}


void Ms1ScanInfo::MergeFrom(const Ms1ScanInfo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:crux_lfq.Ms1ScanInfo)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x00000007u) {
    if (cached_has_bits & 0x00000001u) {
      one_based_scan_number_ = from.one_based_scan_number_;
    }
    if (cached_has_bits & 0x00000002u) {
      zero_based_ms1_scan_index_ = from.zero_based_ms1_scan_index_;
    }
    if (cached_has_bits & 0x00000004u) {
      retention_time_ = from.retention_time_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Ms1ScanInfo::CopyFrom(const Ms1ScanInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:crux_lfq.Ms1ScanInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ms1ScanInfo::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void Ms1ScanInfo::InternalSwap(Ms1ScanInfo* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Ms1ScanInfo, retention_time_)
      + sizeof(Ms1ScanInfo::retention_time_)
      - PROTOBUF_FIELD_OFFSET(Ms1ScanInfo, one_based_scan_number_)>(
          reinterpret_cast<char*>(&one_based_scan_number_),
          reinterpret_cast<char*>(&other->one_based_scan_number_));
}

::PROTOBUF_NAMESPACE_ID::Metadata Ms1ScanInfo::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[0]);
}

// ===================================================================

class IndexedMassSpectralPeak::_Internal {
 public:
  using HasBits = decltype(std::declval<IndexedMassSpectralPeak>()._has_bits_);
  static void set_has_mz(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_intensity(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_zero_based_ms1_scan_index(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_retention_time(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static bool MissingRequiredFields(const HasBits& has_bits) {
    return ((has_bits[0] & 0x0000000f) ^ 0x0000000f) != 0;
  }
};

IndexedMassSpectralPeak::IndexedMassSpectralPeak(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:crux_lfq.IndexedMassSpectralPeak)
}
IndexedMassSpectralPeak::IndexedMassSpectralPeak(const IndexedMassSpectralPeak& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&mz_, &from.mz_,
    static_cast<size_t>(reinterpret_cast<char*>(&zero_based_ms1_scan_index_) -
    reinterpret_cast<char*>(&mz_)) + sizeof(zero_based_ms1_scan_index_));
  // @@protoc_insertion_point(copy_constructor:crux_lfq.IndexedMassSpectralPeak)
}

inline void IndexedMassSpectralPeak::SharedCtor() {
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&mz_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&zero_based_ms1_scan_index_) -
    reinterpret_cast<char*>(&mz_)) + sizeof(zero_based_ms1_scan_index_));
}

IndexedMassSpectralPeak::~IndexedMassSpectralPeak() {
  // @@protoc_insertion_point(destructor:crux_lfq.IndexedMassSpectralPeak)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void IndexedMassSpectralPeak::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void IndexedMassSpectralPeak::ArenaDtor(void* object) {
  IndexedMassSpectralPeak* _this = reinterpret_cast< IndexedMassSpectralPeak* >(object);
  (void)_this;
}
void IndexedMassSpectralPeak::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void IndexedMassSpectralPeak::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void IndexedMassSpectralPeak::Clear() {
// @@protoc_insertion_point(message_clear_start:crux_lfq.IndexedMassSpectralPeak)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    ::memset(&mz_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&zero_based_ms1_scan_index_) -
        reinterpret_cast<char*>(&mz_)) + sizeof(zero_based_ms1_scan_index_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IndexedMassSpectralPeak::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // required double mz = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 9)) {
          _Internal::set_has_mz(&has_bits);
          mz_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // required double intensity = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 17)) {
          _Internal::set_has_intensity(&has_bits);
          intensity_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      // required int32 zero_based_ms1_scan_index = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 24)) {
          _Internal::set_has_zero_based_ms1_scan_index(&has_bits);
          zero_based_ms1_scan_index_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // required double retention_time = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 33)) {
          _Internal::set_has_retention_time(&has_bits);
          retention_time_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr);
          ptr += sizeof(double);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IndexedMassSpectralPeak::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:crux_lfq.IndexedMassSpectralPeak)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // required double mz = 1;
  if (cached_has_bits & 0x00000001u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(1, this->_internal_mz(), target);
  }

  // required double intensity = 2;
  if (cached_has_bits & 0x00000002u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(2, this->_internal_intensity(), target);
  }

  // required int32 zero_based_ms1_scan_index = 3;
  if (cached_has_bits & 0x00000008u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_zero_based_ms1_scan_index(), target);
  }

  // required double retention_time = 4;
  if (cached_has_bits & 0x00000004u) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(4, this->_internal_retention_time(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:crux_lfq.IndexedMassSpectralPeak)
  return target;
}

size_t IndexedMassSpectralPeak::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:crux_lfq.IndexedMassSpectralPeak)
  size_t total_size = 0;

  if (_internal_has_mz()) {
    // required double mz = 1;
    total_size += 1 + 8;
  }

  if (_internal_has_intensity()) {
    // required double intensity = 2;
    total_size += 1 + 8;
  }

  if (_internal_has_retention_time()) {
    // required double retention_time = 4;
    total_size += 1 + 8;
  }

  if (_internal_has_zero_based_ms1_scan_index()) {
    // required int32 zero_based_ms1_scan_index = 3;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_zero_based_ms1_scan_index());
  }

  return total_size;
}
size_t IndexedMassSpectralPeak::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:crux_lfq.IndexedMassSpectralPeak)
  size_t total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required double mz = 1;
    total_size += 1 + 8;

    // required double intensity = 2;
    total_size += 1 + 8;

    // required double retention_time = 4;
    total_size += 1 + 8;

    // required int32 zero_based_ms1_scan_index = 3;
    total_size += ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32SizePlusOne(this->_internal_zero_based_ms1_scan_index());

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IndexedMassSpectralPeak::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    IndexedMassSpectralPeak::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IndexedMassSpectralPeak::GetClassData() const { return &_class_data_; }

void IndexedMassSpectralPeak::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<IndexedMassSpectralPeak *>(to)->MergeFrom(
      static_cast<const IndexedMassSpectralPeak &>(from));
}


void IndexedMassSpectralPeak::MergeFrom(const IndexedMassSpectralPeak& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:crux_lfq.IndexedMassSpectralPeak)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 0x0000000fu) {
    if (cached_has_bits & 0x00000001u) {
      mz_ = from.mz_;
    }
    if (cached_has_bits & 0x00000002u) {
      intensity_ = from.intensity_;
    }
    if (cached_has_bits & 0x00000004u) {
      retention_time_ = from.retention_time_;
    }
    if (cached_has_bits & 0x00000008u) {
      zero_based_ms1_scan_index_ = from.zero_based_ms1_scan_index_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IndexedMassSpectralPeak::CopyFrom(const IndexedMassSpectralPeak& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:crux_lfq.IndexedMassSpectralPeak)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IndexedMassSpectralPeak::IsInitialized() const {
  if (_Internal::MissingRequiredFields(_has_bits_)) return false;
  return true;
}

void IndexedMassSpectralPeak::InternalSwap(IndexedMassSpectralPeak* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(IndexedMassSpectralPeak, zero_based_ms1_scan_index_)
      + sizeof(IndexedMassSpectralPeak::zero_based_ms1_scan_index_)
      - PROTOBUF_FIELD_OFFSET(IndexedMassSpectralPeak, mz_)>(
          reinterpret_cast<char*>(&mz_),
          reinterpret_cast<char*>(&other->mz_));
}

::PROTOBUF_NAMESPACE_ID::Metadata IndexedMassSpectralPeak::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[1]);
}

// ===================================================================

InnerMap_InnerMapEntry_DoNotUse::InnerMap_InnerMapEntry_DoNotUse() {}
InnerMap_InnerMapEntry_DoNotUse::InnerMap_InnerMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void InnerMap_InnerMapEntry_DoNotUse::MergeFrom(const InnerMap_InnerMapEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata InnerMap_InnerMapEntry_DoNotUse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[2]);
}

// ===================================================================

class InnerMap::_Internal {
 public:
};

InnerMap::InnerMap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  inner_map_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:crux_lfq.InnerMap)
}
InnerMap::InnerMap(const InnerMap& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  inner_map_.MergeFrom(from.inner_map_);
  // @@protoc_insertion_point(copy_constructor:crux_lfq.InnerMap)
}

inline void InnerMap::SharedCtor() {
}

InnerMap::~InnerMap() {
  // @@protoc_insertion_point(destructor:crux_lfq.InnerMap)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void InnerMap::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void InnerMap::ArenaDtor(void* object) {
  InnerMap* _this = reinterpret_cast< InnerMap* >(object);
  (void)_this;
  _this->inner_map_. ~MapField();
}
inline void InnerMap::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena) {
  if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &InnerMap::ArenaDtor);
  }
}
void InnerMap::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void InnerMap::Clear() {
// @@protoc_insertion_point(message_clear_start:crux_lfq.InnerMap)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  inner_map_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InnerMap::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<int32, .crux_lfq.IndexedMassSpectralPeak> inner_map = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&inner_map_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InnerMap::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:crux_lfq.InnerMap)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, .crux_lfq.IndexedMassSpectralPeak> inner_map = 1;
  if (!this->_internal_inner_map().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< int32_t, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;

    if (stream->IsSerializationDeterministic() &&
        this->_internal_inner_map().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_inner_map().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >::const_iterator
          it = this->_internal_inner_map().begin();
          it != this->_internal_inner_map().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = InnerMap_InnerMapEntry_DoNotUse::Funcs::InternalSerialize(1, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >::const_iterator
          it = this->_internal_inner_map().begin();
          it != this->_internal_inner_map().end(); ++it) {
        target = InnerMap_InnerMapEntry_DoNotUse::Funcs::InternalSerialize(1, it->first, it->second, target, stream);
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:crux_lfq.InnerMap)
  return target;
}

size_t InnerMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:crux_lfq.InnerMap)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .crux_lfq.IndexedMassSpectralPeak> inner_map = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_inner_map_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >::const_iterator
      it = this->_internal_inner_map().begin();
      it != this->_internal_inner_map().end(); ++it) {
    total_size += InnerMap_InnerMapEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InnerMap::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    InnerMap::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InnerMap::GetClassData() const { return &_class_data_; }

void InnerMap::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<InnerMap *>(to)->MergeFrom(
      static_cast<const InnerMap &>(from));
}


void InnerMap::MergeFrom(const InnerMap& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:crux_lfq.InnerMap)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  inner_map_.MergeFrom(from.inner_map_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InnerMap::CopyFrom(const InnerMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:crux_lfq.InnerMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InnerMap::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(inner_map_)) return false;
  return true;
}

void InnerMap::InternalSwap(InnerMap* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  inner_map_.InternalSwap(&other->inner_map_);
}

::PROTOBUF_NAMESPACE_ID::Metadata InnerMap::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[3]);
}

// ===================================================================

class Ms1ScanInfoList::_Internal {
 public:
};

Ms1ScanInfoList::Ms1ScanInfoList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  ms1_scan_info_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:crux_lfq.Ms1ScanInfoList)
}
Ms1ScanInfoList::Ms1ScanInfoList(const Ms1ScanInfoList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      ms1_scan_info_(from.ms1_scan_info_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:crux_lfq.Ms1ScanInfoList)
}

inline void Ms1ScanInfoList::SharedCtor() {
}

Ms1ScanInfoList::~Ms1ScanInfoList() {
  // @@protoc_insertion_point(destructor:crux_lfq.Ms1ScanInfoList)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void Ms1ScanInfoList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void Ms1ScanInfoList::ArenaDtor(void* object) {
  Ms1ScanInfoList* _this = reinterpret_cast< Ms1ScanInfoList* >(object);
  (void)_this;
}
void Ms1ScanInfoList::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void Ms1ScanInfoList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void Ms1ScanInfoList::Clear() {
// @@protoc_insertion_point(message_clear_start:crux_lfq.Ms1ScanInfoList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ms1_scan_info_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* Ms1ScanInfoList::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .crux_lfq.Ms1ScanInfo ms1_scan_info = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_ms1_scan_info(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* Ms1ScanInfoList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:crux_lfq.Ms1ScanInfoList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .crux_lfq.Ms1ScanInfo ms1_scan_info = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_ms1_scan_info_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, this->_internal_ms1_scan_info(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:crux_lfq.Ms1ScanInfoList)
  return target;
}

size_t Ms1ScanInfoList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:crux_lfq.Ms1ScanInfoList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .crux_lfq.Ms1ScanInfo ms1_scan_info = 1;
  total_size += 1UL * this->_internal_ms1_scan_info_size();
  for (const auto& msg : this->ms1_scan_info_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData Ms1ScanInfoList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    Ms1ScanInfoList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*Ms1ScanInfoList::GetClassData() const { return &_class_data_; }

void Ms1ScanInfoList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<Ms1ScanInfoList *>(to)->MergeFrom(
      static_cast<const Ms1ScanInfoList &>(from));
}


void Ms1ScanInfoList::MergeFrom(const Ms1ScanInfoList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:crux_lfq.Ms1ScanInfoList)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  ms1_scan_info_.MergeFrom(from.ms1_scan_info_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void Ms1ScanInfoList::CopyFrom(const Ms1ScanInfoList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:crux_lfq.Ms1ScanInfoList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Ms1ScanInfoList::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(ms1_scan_info_))
    return false;
  return true;
}

void Ms1ScanInfoList::InternalSwap(Ms1ScanInfoList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ms1_scan_info_.InternalSwap(&other->ms1_scan_info_);
}

::PROTOBUF_NAMESPACE_ID::Metadata Ms1ScanInfoList::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[4]);
}

// ===================================================================

IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse() {}
IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::MergeFrom(const IndexedSpectralResults_IndexedPeaksEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[5]);
}

// ===================================================================

IndexedSpectralResults_Ms1ScansEntry_DoNotUse::IndexedSpectralResults_Ms1ScansEntry_DoNotUse() {}
IndexedSpectralResults_Ms1ScansEntry_DoNotUse::IndexedSpectralResults_Ms1ScansEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena)
    : SuperType(arena) {}
void IndexedSpectralResults_Ms1ScansEntry_DoNotUse::MergeFrom(const IndexedSpectralResults_Ms1ScansEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::PROTOBUF_NAMESPACE_ID::Metadata IndexedSpectralResults_Ms1ScansEntry_DoNotUse::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[6]);
}

// ===================================================================

class IndexedSpectralResults::_Internal {
 public:
};

IndexedSpectralResults::IndexedSpectralResults(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned),
  indexed_peaks_(arena),
  ms1_scans_(arena) {
  SharedCtor();
  if (!is_message_owned) {
    RegisterArenaDtor(arena);
  }
  // @@protoc_insertion_point(arena_constructor:crux_lfq.IndexedSpectralResults)
}
IndexedSpectralResults::IndexedSpectralResults(const IndexedSpectralResults& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  indexed_peaks_.MergeFrom(from.indexed_peaks_);
  ms1_scans_.MergeFrom(from.ms1_scans_);
  // @@protoc_insertion_point(copy_constructor:crux_lfq.IndexedSpectralResults)
}

inline void IndexedSpectralResults::SharedCtor() {
}

IndexedSpectralResults::~IndexedSpectralResults() {
  // @@protoc_insertion_point(destructor:crux_lfq.IndexedSpectralResults)
  if (GetArenaForAllocation() != nullptr) return;
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

inline void IndexedSpectralResults::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
}

void IndexedSpectralResults::ArenaDtor(void* object) {
  IndexedSpectralResults* _this = reinterpret_cast< IndexedSpectralResults* >(object);
  (void)_this;
  _this->indexed_peaks_. ~MapField();
  _this->ms1_scans_. ~MapField();
}
inline void IndexedSpectralResults::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena) {
  if (arena != nullptr) {
    arena->OwnCustomDestructor(this, &IndexedSpectralResults::ArenaDtor);
  }
}
void IndexedSpectralResults::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void IndexedSpectralResults::Clear() {
// @@protoc_insertion_point(message_clear_start:crux_lfq.IndexedSpectralResults)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  indexed_peaks_.Clear();
  ms1_scans_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* IndexedSpectralResults::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // map<int32, .crux_lfq.InnerMap> indexed_peaks = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&indexed_peaks_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // map<string, .crux_lfq.Ms1ScanInfoList> ms1_scans = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(&ms1_scans_, ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* IndexedSpectralResults::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:crux_lfq.IndexedSpectralResults)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // map<int32, .crux_lfq.InnerMap> indexed_peaks = 1;
  if (!this->_internal_indexed_peaks().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >::const_pointer
        ConstPtr;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::SortItem< int32_t, ConstPtr > SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByFirstField<SortItem> Less;

    if (stream->IsSerializationDeterministic() &&
        this->_internal_indexed_peaks().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_indexed_peaks().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >::const_iterator
          it = this->_internal_indexed_peaks().begin();
          it != this->_internal_indexed_peaks().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::Funcs::InternalSerialize(1, items[static_cast<ptrdiff_t>(i)].second->first, items[static_cast<ptrdiff_t>(i)].second->second, target, stream);
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >::const_iterator
          it = this->_internal_indexed_peaks().begin();
          it != this->_internal_indexed_peaks().end(); ++it) {
        target = IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::Funcs::InternalSerialize(1, it->first, it->second, target, stream);
      }
    }
  }

  // map<string, .crux_lfq.Ms1ScanInfoList> ms1_scans = 2;
  if (!this->_internal_ms1_scans().empty()) {
    typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::PROTOBUF_NAMESPACE_ID::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        (void)p;
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::VerifyUTF8StringNamedField(
          p->first.data(), static_cast<int>(p->first.length()),
          ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::SERIALIZE,
          "crux_lfq.IndexedSpectralResults.Ms1ScansEntry.key");
      }
    };

    if (stream->IsSerializationDeterministic() &&
        this->_internal_ms1_scans().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->_internal_ms1_scans().size()]);
      typedef ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >::size_type size_type;
      size_type n = 0;
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >::const_iterator
          it = this->_internal_ms1_scans().begin();
          it != this->_internal_ms1_scans().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      for (size_type i = 0; i < n; i++) {
        target = IndexedSpectralResults_Ms1ScansEntry_DoNotUse::Funcs::InternalSerialize(2, items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second, target, stream);
        Utf8Check::Check(&(*items[static_cast<ptrdiff_t>(i)]));
      }
    } else {
      for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >::const_iterator
          it = this->_internal_ms1_scans().begin();
          it != this->_internal_ms1_scans().end(); ++it) {
        target = IndexedSpectralResults_Ms1ScansEntry_DoNotUse::Funcs::InternalSerialize(2, it->first, it->second, target, stream);
        Utf8Check::Check(&(*it));
      }
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:crux_lfq.IndexedSpectralResults)
  return target;
}

size_t IndexedSpectralResults::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:crux_lfq.IndexedSpectralResults)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // map<int32, .crux_lfq.InnerMap> indexed_peaks = 1;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_indexed_peaks_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >::const_iterator
      it = this->_internal_indexed_peaks().begin();
      it != this->_internal_indexed_peaks().end(); ++it) {
    total_size += IndexedSpectralResults_IndexedPeaksEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  // map<string, .crux_lfq.Ms1ScanInfoList> ms1_scans = 2;
  total_size += 1 *
      ::PROTOBUF_NAMESPACE_ID::internal::FromIntSize(this->_internal_ms1_scans_size());
  for (::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >::const_iterator
      it = this->_internal_ms1_scans().begin();
      it != this->_internal_ms1_scans().end(); ++it) {
    total_size += IndexedSpectralResults_Ms1ScansEntry_DoNotUse::Funcs::ByteSizeLong(it->first, it->second);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData IndexedSpectralResults::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSizeCheck,
    IndexedSpectralResults::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*IndexedSpectralResults::GetClassData() const { return &_class_data_; }

void IndexedSpectralResults::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to,
                      const ::PROTOBUF_NAMESPACE_ID::Message& from) {
  static_cast<IndexedSpectralResults *>(to)->MergeFrom(
      static_cast<const IndexedSpectralResults &>(from));
}


void IndexedSpectralResults::MergeFrom(const IndexedSpectralResults& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:crux_lfq.IndexedSpectralResults)
  GOOGLE_DCHECK_NE(&from, this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  indexed_peaks_.MergeFrom(from.indexed_peaks_);
  ms1_scans_.MergeFrom(from.ms1_scans_);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void IndexedSpectralResults::CopyFrom(const IndexedSpectralResults& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:crux_lfq.IndexedSpectralResults)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool IndexedSpectralResults::IsInitialized() const {
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(indexed_peaks_)) return false;
  if (!::PROTOBUF_NAMESPACE_ID::internal::AllAreInitialized(ms1_scans_)) return false;
  return true;
}

void IndexedSpectralResults::InternalSwap(IndexedSpectralResults* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  indexed_peaks_.InternalSwap(&other->indexed_peaks_);
  ms1_scans_.InternalSwap(&other->ms1_scans_);
}

::PROTOBUF_NAMESPACE_ID::Metadata IndexedSpectralResults::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_getter, &descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto_once,
      file_level_metadata_indexed_5fmass_5fspectral_5fpeak_2eproto[7]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace crux_lfq
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::crux_lfq::Ms1ScanInfo* Arena::CreateMaybeMessage< ::crux_lfq::Ms1ScanInfo >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::Ms1ScanInfo >(arena);
}
template<> PROTOBUF_NOINLINE ::crux_lfq::IndexedMassSpectralPeak* Arena::CreateMaybeMessage< ::crux_lfq::IndexedMassSpectralPeak >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::IndexedMassSpectralPeak >(arena);
}
template<> PROTOBUF_NOINLINE ::crux_lfq::InnerMap_InnerMapEntry_DoNotUse* Arena::CreateMaybeMessage< ::crux_lfq::InnerMap_InnerMapEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::InnerMap_InnerMapEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::crux_lfq::InnerMap* Arena::CreateMaybeMessage< ::crux_lfq::InnerMap >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::InnerMap >(arena);
}
template<> PROTOBUF_NOINLINE ::crux_lfq::Ms1ScanInfoList* Arena::CreateMaybeMessage< ::crux_lfq::Ms1ScanInfoList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::Ms1ScanInfoList >(arena);
}
template<> PROTOBUF_NOINLINE ::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse* Arena::CreateMaybeMessage< ::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse* Arena::CreateMaybeMessage< ::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse >(arena);
}
template<> PROTOBUF_NOINLINE ::crux_lfq::IndexedSpectralResults* Arena::CreateMaybeMessage< ::crux_lfq::IndexedSpectralResults >(Arena* arena) {
  return Arena::CreateMessageInternal< ::crux_lfq::IndexedSpectralResults >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
