# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: indexed_mass_spectral_peak.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n indexed_mass_spectral_peak.proto\x12\x08\x63rux_lfq\"g\n\x0bMs1ScanInfo\x12\x1d\n\x15one_based_scan_number\x18\x01 \x02(\x05\x12!\n\x19zero_based_ms1_scan_index\x18\x02 \x02(\x05\x12\x16\n\x0eretention_time\x18\x03 \x02(\x01\"s\n\x17IndexedMassSpectralPeak\x12\n\n\x02mz\x18\x01 \x02(\x01\x12\x11\n\tintensity\x18\x02 \x02(\x01\x12!\n\x19zero_based_ms1_scan_index\x18\x03 \x02(\x05\x12\x16\n\x0eretention_time\x18\x04 \x02(\x01\"\x93\x01\n\x08InnerMap\x12\x33\n\tinner_map\x18\x01 \x03(\x0b\x32 .crux_lfq.InnerMap.InnerMapEntry\x1aR\n\rInnerMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\x30\n\x05value\x18\x02 \x01(\x0b\x32!.crux_lfq.IndexedMassSpectralPeak:\x02\x38\x01\"?\n\x0fMs1ScanInfoList\x12,\n\rms1_scan_info\x18\x01 \x03(\x0b\x32\x15.crux_lfq.Ms1ScanInfo\"\xbb\x02\n\x16IndexedSpectralResults\x12I\n\rindexed_peaks\x18\x01 \x03(\x0b\x32\x32.crux_lfq.IndexedSpectralResults.IndexedPeaksEntry\x12\x41\n\tms1_scans\x18\x02 \x03(\x0b\x32..crux_lfq.IndexedSpectralResults.Ms1ScansEntry\x1aG\n\x11IndexedPeaksEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12!\n\x05value\x18\x02 \x01(\x0b\x32\x12.crux_lfq.InnerMap:\x02\x38\x01\x1aJ\n\rMs1ScansEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.crux_lfq.Ms1ScanInfoList:\x02\x38\x01\x42\x02H\x01')



_MS1SCANINFO = DESCRIPTOR.message_types_by_name['Ms1ScanInfo']
_INDEXEDMASSSPECTRALPEAK = DESCRIPTOR.message_types_by_name['IndexedMassSpectralPeak']
_INNERMAP = DESCRIPTOR.message_types_by_name['InnerMap']
_INNERMAP_INNERMAPENTRY = _INNERMAP.nested_types_by_name['InnerMapEntry']
_MS1SCANINFOLIST = DESCRIPTOR.message_types_by_name['Ms1ScanInfoList']
_INDEXEDSPECTRALRESULTS = DESCRIPTOR.message_types_by_name['IndexedSpectralResults']
_INDEXEDSPECTRALRESULTS_INDEXEDPEAKSENTRY = _INDEXEDSPECTRALRESULTS.nested_types_by_name['IndexedPeaksEntry']
_INDEXEDSPECTRALRESULTS_MS1SCANSENTRY = _INDEXEDSPECTRALRESULTS.nested_types_by_name['Ms1ScansEntry']
Ms1ScanInfo = _reflection.GeneratedProtocolMessageType('Ms1ScanInfo', (_message.Message,), {
  'DESCRIPTOR' : _MS1SCANINFO,
  '__module__' : 'indexed_mass_spectral_peak_pb2'
  # @@protoc_insertion_point(class_scope:crux_lfq.Ms1ScanInfo)
  })
_sym_db.RegisterMessage(Ms1ScanInfo)

IndexedMassSpectralPeak = _reflection.GeneratedProtocolMessageType('IndexedMassSpectralPeak', (_message.Message,), {
  'DESCRIPTOR' : _INDEXEDMASSSPECTRALPEAK,
  '__module__' : 'indexed_mass_spectral_peak_pb2'
  # @@protoc_insertion_point(class_scope:crux_lfq.IndexedMassSpectralPeak)
  })
_sym_db.RegisterMessage(IndexedMassSpectralPeak)

InnerMap = _reflection.GeneratedProtocolMessageType('InnerMap', (_message.Message,), {

  'InnerMapEntry' : _reflection.GeneratedProtocolMessageType('InnerMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _INNERMAP_INNERMAPENTRY,
    '__module__' : 'indexed_mass_spectral_peak_pb2'
    # @@protoc_insertion_point(class_scope:crux_lfq.InnerMap.InnerMapEntry)
    })
  ,
  'DESCRIPTOR' : _INNERMAP,
  '__module__' : 'indexed_mass_spectral_peak_pb2'
  # @@protoc_insertion_point(class_scope:crux_lfq.InnerMap)
  })
_sym_db.RegisterMessage(InnerMap)
_sym_db.RegisterMessage(InnerMap.InnerMapEntry)

Ms1ScanInfoList = _reflection.GeneratedProtocolMessageType('Ms1ScanInfoList', (_message.Message,), {
  'DESCRIPTOR' : _MS1SCANINFOLIST,
  '__module__' : 'indexed_mass_spectral_peak_pb2'
  # @@protoc_insertion_point(class_scope:crux_lfq.Ms1ScanInfoList)
  })
_sym_db.RegisterMessage(Ms1ScanInfoList)

IndexedSpectralResults = _reflection.GeneratedProtocolMessageType('IndexedSpectralResults', (_message.Message,), {

  'IndexedPeaksEntry' : _reflection.GeneratedProtocolMessageType('IndexedPeaksEntry', (_message.Message,), {
    'DESCRIPTOR' : _INDEXEDSPECTRALRESULTS_INDEXEDPEAKSENTRY,
    '__module__' : 'indexed_mass_spectral_peak_pb2'
    # @@protoc_insertion_point(class_scope:crux_lfq.IndexedSpectralResults.IndexedPeaksEntry)
    })
  ,

  'Ms1ScansEntry' : _reflection.GeneratedProtocolMessageType('Ms1ScansEntry', (_message.Message,), {
    'DESCRIPTOR' : _INDEXEDSPECTRALRESULTS_MS1SCANSENTRY,
    '__module__' : 'indexed_mass_spectral_peak_pb2'
    # @@protoc_insertion_point(class_scope:crux_lfq.IndexedSpectralResults.Ms1ScansEntry)
    })
  ,
  'DESCRIPTOR' : _INDEXEDSPECTRALRESULTS,
  '__module__' : 'indexed_mass_spectral_peak_pb2'
  # @@protoc_insertion_point(class_scope:crux_lfq.IndexedSpectralResults)
  })
_sym_db.RegisterMessage(IndexedSpectralResults)
_sym_db.RegisterMessage(IndexedSpectralResults.IndexedPeaksEntry)
_sym_db.RegisterMessage(IndexedSpectralResults.Ms1ScansEntry)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\001'
  _INNERMAP_INNERMAPENTRY._options = None
  _INNERMAP_INNERMAPENTRY._serialized_options = b'8\001'
  _INDEXEDSPECTRALRESULTS_INDEXEDPEAKSENTRY._options = None
  _INDEXEDSPECTRALRESULTS_INDEXEDPEAKSENTRY._serialized_options = b'8\001'
  _INDEXEDSPECTRALRESULTS_MS1SCANSENTRY._options = None
  _INDEXEDSPECTRALRESULTS_MS1SCANSENTRY._serialized_options = b'8\001'
  _MS1SCANINFO._serialized_start=46
  _MS1SCANINFO._serialized_end=149
  _INDEXEDMASSSPECTRALPEAK._serialized_start=151
  _INDEXEDMASSSPECTRALPEAK._serialized_end=266
  _INNERMAP._serialized_start=269
  _INNERMAP._serialized_end=416
  _INNERMAP_INNERMAPENTRY._serialized_start=334
  _INNERMAP_INNERMAPENTRY._serialized_end=416
  _MS1SCANINFOLIST._serialized_start=418
  _MS1SCANINFOLIST._serialized_end=481
  _INDEXEDSPECTRALRESULTS._serialized_start=484
  _INDEXEDSPECTRALRESULTS._serialized_end=799
  _INDEXEDSPECTRALRESULTS_INDEXEDPEAKSENTRY._serialized_start=652
  _INDEXEDSPECTRALRESULTS_INDEXEDPEAKSENTRY._serialized_end=723
  _INDEXEDSPECTRALRESULTS_MS1SCANSENTRY._serialized_start=725
  _INDEXEDSPECTRALRESULTS_MS1SCANSENTRY._serialized_end=799
# @@protoc_insertion_point(module_scope)
