// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: indexed_mass_spectral_peak.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_indexed_5fmass_5fspectral_5fpeak_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_indexed_5fmass_5fspectral_5fpeak_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_indexed_5fmass_5fspectral_5fpeak_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[8]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_indexed_5fmass_5fspectral_5fpeak_2eproto;
namespace crux_lfq {
class IndexedMassSpectralPeak;
struct IndexedMassSpectralPeakDefaultTypeInternal;
extern IndexedMassSpectralPeakDefaultTypeInternal _IndexedMassSpectralPeak_default_instance_;
class IndexedSpectralResults;
struct IndexedSpectralResultsDefaultTypeInternal;
extern IndexedSpectralResultsDefaultTypeInternal _IndexedSpectralResults_default_instance_;
class IndexedSpectralResults_IndexedPeaksEntry_DoNotUse;
struct IndexedSpectralResults_IndexedPeaksEntry_DoNotUseDefaultTypeInternal;
extern IndexedSpectralResults_IndexedPeaksEntry_DoNotUseDefaultTypeInternal _IndexedSpectralResults_IndexedPeaksEntry_DoNotUse_default_instance_;
class IndexedSpectralResults_Ms1ScansEntry_DoNotUse;
struct IndexedSpectralResults_Ms1ScansEntry_DoNotUseDefaultTypeInternal;
extern IndexedSpectralResults_Ms1ScansEntry_DoNotUseDefaultTypeInternal _IndexedSpectralResults_Ms1ScansEntry_DoNotUse_default_instance_;
class InnerMap;
struct InnerMapDefaultTypeInternal;
extern InnerMapDefaultTypeInternal _InnerMap_default_instance_;
class InnerMap_InnerMapEntry_DoNotUse;
struct InnerMap_InnerMapEntry_DoNotUseDefaultTypeInternal;
extern InnerMap_InnerMapEntry_DoNotUseDefaultTypeInternal _InnerMap_InnerMapEntry_DoNotUse_default_instance_;
class Ms1ScanInfo;
struct Ms1ScanInfoDefaultTypeInternal;
extern Ms1ScanInfoDefaultTypeInternal _Ms1ScanInfo_default_instance_;
class Ms1ScanInfoList;
struct Ms1ScanInfoListDefaultTypeInternal;
extern Ms1ScanInfoListDefaultTypeInternal _Ms1ScanInfoList_default_instance_;
}  // namespace crux_lfq
PROTOBUF_NAMESPACE_OPEN
template<> ::crux_lfq::IndexedMassSpectralPeak* Arena::CreateMaybeMessage<::crux_lfq::IndexedMassSpectralPeak>(Arena*);
template<> ::crux_lfq::IndexedSpectralResults* Arena::CreateMaybeMessage<::crux_lfq::IndexedSpectralResults>(Arena*);
template<> ::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse* Arena::CreateMaybeMessage<::crux_lfq::IndexedSpectralResults_IndexedPeaksEntry_DoNotUse>(Arena*);
template<> ::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse* Arena::CreateMaybeMessage<::crux_lfq::IndexedSpectralResults_Ms1ScansEntry_DoNotUse>(Arena*);
template<> ::crux_lfq::InnerMap* Arena::CreateMaybeMessage<::crux_lfq::InnerMap>(Arena*);
template<> ::crux_lfq::InnerMap_InnerMapEntry_DoNotUse* Arena::CreateMaybeMessage<::crux_lfq::InnerMap_InnerMapEntry_DoNotUse>(Arena*);
template<> ::crux_lfq::Ms1ScanInfo* Arena::CreateMaybeMessage<::crux_lfq::Ms1ScanInfo>(Arena*);
template<> ::crux_lfq::Ms1ScanInfoList* Arena::CreateMaybeMessage<::crux_lfq::Ms1ScanInfoList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace crux_lfq {

// ===================================================================

class Ms1ScanInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crux_lfq.Ms1ScanInfo) */ {
 public:
  inline Ms1ScanInfo() : Ms1ScanInfo(nullptr) {}
  ~Ms1ScanInfo() override;
  explicit constexpr Ms1ScanInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Ms1ScanInfo(const Ms1ScanInfo& from);
  Ms1ScanInfo(Ms1ScanInfo&& from) noexcept
    : Ms1ScanInfo() {
    *this = ::std::move(from);
  }

  inline Ms1ScanInfo& operator=(const Ms1ScanInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ms1ScanInfo& operator=(Ms1ScanInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ms1ScanInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ms1ScanInfo* internal_default_instance() {
    return reinterpret_cast<const Ms1ScanInfo*>(
               &_Ms1ScanInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Ms1ScanInfo& a, Ms1ScanInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(Ms1ScanInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ms1ScanInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ms1ScanInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Ms1ScanInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Ms1ScanInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Ms1ScanInfo& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ms1ScanInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crux_lfq.Ms1ScanInfo";
  }
  protected:
  explicit Ms1ScanInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOneBasedScanNumberFieldNumber = 1,
    kZeroBasedMs1ScanIndexFieldNumber = 2,
    kRetentionTimeFieldNumber = 3,
  };
  // required int32 one_based_scan_number = 1;
  bool has_one_based_scan_number() const;
  private:
  bool _internal_has_one_based_scan_number() const;
  public:
  void clear_one_based_scan_number();
  int32_t one_based_scan_number() const;
  void set_one_based_scan_number(int32_t value);
  private:
  int32_t _internal_one_based_scan_number() const;
  void _internal_set_one_based_scan_number(int32_t value);
  public:

  // required int32 zero_based_ms1_scan_index = 2;
  bool has_zero_based_ms1_scan_index() const;
  private:
  bool _internal_has_zero_based_ms1_scan_index() const;
  public:
  void clear_zero_based_ms1_scan_index();
  int32_t zero_based_ms1_scan_index() const;
  void set_zero_based_ms1_scan_index(int32_t value);
  private:
  int32_t _internal_zero_based_ms1_scan_index() const;
  void _internal_set_zero_based_ms1_scan_index(int32_t value);
  public:

  // required double retention_time = 3;
  bool has_retention_time() const;
  private:
  bool _internal_has_retention_time() const;
  public:
  void clear_retention_time();
  double retention_time() const;
  void set_retention_time(double value);
  private:
  double _internal_retention_time() const;
  void _internal_set_retention_time(double value);
  public:

  // @@protoc_insertion_point(class_scope:crux_lfq.Ms1ScanInfo)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  int32_t one_based_scan_number_;
  int32_t zero_based_ms1_scan_index_;
  double retention_time_;
  friend struct ::TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto;
};
// -------------------------------------------------------------------

class IndexedMassSpectralPeak final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crux_lfq.IndexedMassSpectralPeak) */ {
 public:
  inline IndexedMassSpectralPeak() : IndexedMassSpectralPeak(nullptr) {}
  ~IndexedMassSpectralPeak() override;
  explicit constexpr IndexedMassSpectralPeak(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IndexedMassSpectralPeak(const IndexedMassSpectralPeak& from);
  IndexedMassSpectralPeak(IndexedMassSpectralPeak&& from) noexcept
    : IndexedMassSpectralPeak() {
    *this = ::std::move(from);
  }

  inline IndexedMassSpectralPeak& operator=(const IndexedMassSpectralPeak& from) {
    CopyFrom(from);
    return *this;
  }
  inline IndexedMassSpectralPeak& operator=(IndexedMassSpectralPeak&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IndexedMassSpectralPeak& default_instance() {
    return *internal_default_instance();
  }
  static inline const IndexedMassSpectralPeak* internal_default_instance() {
    return reinterpret_cast<const IndexedMassSpectralPeak*>(
               &_IndexedMassSpectralPeak_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(IndexedMassSpectralPeak& a, IndexedMassSpectralPeak& b) {
    a.Swap(&b);
  }
  inline void Swap(IndexedMassSpectralPeak* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IndexedMassSpectralPeak* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IndexedMassSpectralPeak* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IndexedMassSpectralPeak>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IndexedMassSpectralPeak& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const IndexedMassSpectralPeak& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IndexedMassSpectralPeak* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crux_lfq.IndexedMassSpectralPeak";
  }
  protected:
  explicit IndexedMassSpectralPeak(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMzFieldNumber = 1,
    kIntensityFieldNumber = 2,
    kRetentionTimeFieldNumber = 4,
    kZeroBasedMs1ScanIndexFieldNumber = 3,
  };
  // required double mz = 1;
  bool has_mz() const;
  private:
  bool _internal_has_mz() const;
  public:
  void clear_mz();
  double mz() const;
  void set_mz(double value);
  private:
  double _internal_mz() const;
  void _internal_set_mz(double value);
  public:

  // required double intensity = 2;
  bool has_intensity() const;
  private:
  bool _internal_has_intensity() const;
  public:
  void clear_intensity();
  double intensity() const;
  void set_intensity(double value);
  private:
  double _internal_intensity() const;
  void _internal_set_intensity(double value);
  public:

  // required double retention_time = 4;
  bool has_retention_time() const;
  private:
  bool _internal_has_retention_time() const;
  public:
  void clear_retention_time();
  double retention_time() const;
  void set_retention_time(double value);
  private:
  double _internal_retention_time() const;
  void _internal_set_retention_time(double value);
  public:

  // required int32 zero_based_ms1_scan_index = 3;
  bool has_zero_based_ms1_scan_index() const;
  private:
  bool _internal_has_zero_based_ms1_scan_index() const;
  public:
  void clear_zero_based_ms1_scan_index();
  int32_t zero_based_ms1_scan_index() const;
  void set_zero_based_ms1_scan_index(int32_t value);
  private:
  int32_t _internal_zero_based_ms1_scan_index() const;
  void _internal_set_zero_based_ms1_scan_index(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:crux_lfq.IndexedMassSpectralPeak)
 private:
  class _Internal;

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  double mz_;
  double intensity_;
  double retention_time_;
  int32_t zero_based_ms1_scan_index_;
  friend struct ::TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto;
};
// -------------------------------------------------------------------

class InnerMap_InnerMapEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InnerMap_InnerMapEntry_DoNotUse, 
    int32_t, ::crux_lfq::IndexedMassSpectralPeak,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<InnerMap_InnerMapEntry_DoNotUse, 
    int32_t, ::crux_lfq::IndexedMassSpectralPeak,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  InnerMap_InnerMapEntry_DoNotUse();
  explicit constexpr InnerMap_InnerMapEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit InnerMap_InnerMapEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const InnerMap_InnerMapEntry_DoNotUse& other);
  static const InnerMap_InnerMapEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const InnerMap_InnerMapEntry_DoNotUse*>(&_InnerMap_InnerMapEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
};

// -------------------------------------------------------------------

class InnerMap final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crux_lfq.InnerMap) */ {
 public:
  inline InnerMap() : InnerMap(nullptr) {}
  ~InnerMap() override;
  explicit constexpr InnerMap(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InnerMap(const InnerMap& from);
  InnerMap(InnerMap&& from) noexcept
    : InnerMap() {
    *this = ::std::move(from);
  }

  inline InnerMap& operator=(const InnerMap& from) {
    CopyFrom(from);
    return *this;
  }
  inline InnerMap& operator=(InnerMap&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InnerMap& default_instance() {
    return *internal_default_instance();
  }
  static inline const InnerMap* internal_default_instance() {
    return reinterpret_cast<const InnerMap*>(
               &_InnerMap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(InnerMap& a, InnerMap& b) {
    a.Swap(&b);
  }
  inline void Swap(InnerMap* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InnerMap* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InnerMap* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InnerMap>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InnerMap& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const InnerMap& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InnerMap* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crux_lfq.InnerMap";
  }
  protected:
  explicit InnerMap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kInnerMapFieldNumber = 1,
  };
  // map<int32, .crux_lfq.IndexedMassSpectralPeak> inner_map = 1;
  int inner_map_size() const;
  private:
  int _internal_inner_map_size() const;
  public:
  void clear_inner_map();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >&
      _internal_inner_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >*
      _internal_mutable_inner_map();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >&
      inner_map() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >*
      mutable_inner_map();

  // @@protoc_insertion_point(class_scope:crux_lfq.InnerMap)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      InnerMap_InnerMapEntry_DoNotUse,
      int32_t, ::crux_lfq::IndexedMassSpectralPeak,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> inner_map_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto;
};
// -------------------------------------------------------------------

class Ms1ScanInfoList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crux_lfq.Ms1ScanInfoList) */ {
 public:
  inline Ms1ScanInfoList() : Ms1ScanInfoList(nullptr) {}
  ~Ms1ScanInfoList() override;
  explicit constexpr Ms1ScanInfoList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Ms1ScanInfoList(const Ms1ScanInfoList& from);
  Ms1ScanInfoList(Ms1ScanInfoList&& from) noexcept
    : Ms1ScanInfoList() {
    *this = ::std::move(from);
  }

  inline Ms1ScanInfoList& operator=(const Ms1ScanInfoList& from) {
    CopyFrom(from);
    return *this;
  }
  inline Ms1ScanInfoList& operator=(Ms1ScanInfoList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Ms1ScanInfoList& default_instance() {
    return *internal_default_instance();
  }
  static inline const Ms1ScanInfoList* internal_default_instance() {
    return reinterpret_cast<const Ms1ScanInfoList*>(
               &_Ms1ScanInfoList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Ms1ScanInfoList& a, Ms1ScanInfoList& b) {
    a.Swap(&b);
  }
  inline void Swap(Ms1ScanInfoList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Ms1ScanInfoList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Ms1ScanInfoList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Ms1ScanInfoList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Ms1ScanInfoList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Ms1ScanInfoList& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ms1ScanInfoList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crux_lfq.Ms1ScanInfoList";
  }
  protected:
  explicit Ms1ScanInfoList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMs1ScanInfoFieldNumber = 1,
  };
  // repeated .crux_lfq.Ms1ScanInfo ms1_scan_info = 1;
  int ms1_scan_info_size() const;
  private:
  int _internal_ms1_scan_info_size() const;
  public:
  void clear_ms1_scan_info();
  ::crux_lfq::Ms1ScanInfo* mutable_ms1_scan_info(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crux_lfq::Ms1ScanInfo >*
      mutable_ms1_scan_info();
  private:
  const ::crux_lfq::Ms1ScanInfo& _internal_ms1_scan_info(int index) const;
  ::crux_lfq::Ms1ScanInfo* _internal_add_ms1_scan_info();
  public:
  const ::crux_lfq::Ms1ScanInfo& ms1_scan_info(int index) const;
  ::crux_lfq::Ms1ScanInfo* add_ms1_scan_info();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crux_lfq::Ms1ScanInfo >&
      ms1_scan_info() const;

  // @@protoc_insertion_point(class_scope:crux_lfq.Ms1ScanInfoList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crux_lfq::Ms1ScanInfo > ms1_scan_info_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto;
};
// -------------------------------------------------------------------

class IndexedSpectralResults_IndexedPeaksEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<IndexedSpectralResults_IndexedPeaksEntry_DoNotUse, 
    int32_t, ::crux_lfq::InnerMap,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<IndexedSpectralResults_IndexedPeaksEntry_DoNotUse, 
    int32_t, ::crux_lfq::InnerMap,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  IndexedSpectralResults_IndexedPeaksEntry_DoNotUse();
  explicit constexpr IndexedSpectralResults_IndexedPeaksEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit IndexedSpectralResults_IndexedPeaksEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const IndexedSpectralResults_IndexedPeaksEntry_DoNotUse& other);
  static const IndexedSpectralResults_IndexedPeaksEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const IndexedSpectralResults_IndexedPeaksEntry_DoNotUse*>(&_IndexedSpectralResults_IndexedPeaksEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
};

// -------------------------------------------------------------------

class IndexedSpectralResults_Ms1ScansEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<IndexedSpectralResults_Ms1ScansEntry_DoNotUse, 
    std::string, ::crux_lfq::Ms1ScanInfoList,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<IndexedSpectralResults_Ms1ScansEntry_DoNotUse, 
    std::string, ::crux_lfq::Ms1ScanInfoList,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> SuperType;
  IndexedSpectralResults_Ms1ScansEntry_DoNotUse();
  explicit constexpr IndexedSpectralResults_Ms1ScansEntry_DoNotUse(
      ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);
  explicit IndexedSpectralResults_Ms1ScansEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const IndexedSpectralResults_Ms1ScansEntry_DoNotUse& other);
  static const IndexedSpectralResults_Ms1ScansEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const IndexedSpectralResults_Ms1ScansEntry_DoNotUse*>(&_IndexedSpectralResults_Ms1ScansEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(std::string* s) {
#ifndef NDEBUG
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
       s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "crux_lfq.IndexedSpectralResults.Ms1ScansEntry.key");
#else
    (void) s;
#endif
    return true;
 }
  static bool ValidateValue(void*) { return true; }
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
};

// -------------------------------------------------------------------

class IndexedSpectralResults final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:crux_lfq.IndexedSpectralResults) */ {
 public:
  inline IndexedSpectralResults() : IndexedSpectralResults(nullptr) {}
  ~IndexedSpectralResults() override;
  explicit constexpr IndexedSpectralResults(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  IndexedSpectralResults(const IndexedSpectralResults& from);
  IndexedSpectralResults(IndexedSpectralResults&& from) noexcept
    : IndexedSpectralResults() {
    *this = ::std::move(from);
  }

  inline IndexedSpectralResults& operator=(const IndexedSpectralResults& from) {
    CopyFrom(from);
    return *this;
  }
  inline IndexedSpectralResults& operator=(IndexedSpectralResults&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const IndexedSpectralResults& default_instance() {
    return *internal_default_instance();
  }
  static inline const IndexedSpectralResults* internal_default_instance() {
    return reinterpret_cast<const IndexedSpectralResults*>(
               &_IndexedSpectralResults_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    7;

  friend void swap(IndexedSpectralResults& a, IndexedSpectralResults& b) {
    a.Swap(&b);
  }
  inline void Swap(IndexedSpectralResults* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(IndexedSpectralResults* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  IndexedSpectralResults* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<IndexedSpectralResults>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const IndexedSpectralResults& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const IndexedSpectralResults& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(IndexedSpectralResults* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "crux_lfq.IndexedSpectralResults";
  }
  protected:
  explicit IndexedSpectralResults(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kIndexedPeaksFieldNumber = 1,
    kMs1ScansFieldNumber = 2,
  };
  // map<int32, .crux_lfq.InnerMap> indexed_peaks = 1;
  int indexed_peaks_size() const;
  private:
  int _internal_indexed_peaks_size() const;
  public:
  void clear_indexed_peaks();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >&
      _internal_indexed_peaks() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >*
      _internal_mutable_indexed_peaks();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >&
      indexed_peaks() const;
  ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >*
      mutable_indexed_peaks();

  // map<string, .crux_lfq.Ms1ScanInfoList> ms1_scans = 2;
  int ms1_scans_size() const;
  private:
  int _internal_ms1_scans_size() const;
  public:
  void clear_ms1_scans();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >&
      _internal_ms1_scans() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >*
      _internal_mutable_ms1_scans();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >&
      ms1_scans() const;
  ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >*
      mutable_ms1_scans();

  // @@protoc_insertion_point(class_scope:crux_lfq.IndexedSpectralResults)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      IndexedSpectralResults_IndexedPeaksEntry_DoNotUse,
      int32_t, ::crux_lfq::InnerMap,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> indexed_peaks_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      IndexedSpectralResults_Ms1ScansEntry_DoNotUse,
      std::string, ::crux_lfq::Ms1ScanInfoList,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_MESSAGE> ms1_scans_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_indexed_5fmass_5fspectral_5fpeak_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Ms1ScanInfo

// required int32 one_based_scan_number = 1;
inline bool Ms1ScanInfo::_internal_has_one_based_scan_number() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Ms1ScanInfo::has_one_based_scan_number() const {
  return _internal_has_one_based_scan_number();
}
inline void Ms1ScanInfo::clear_one_based_scan_number() {
  one_based_scan_number_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline int32_t Ms1ScanInfo::_internal_one_based_scan_number() const {
  return one_based_scan_number_;
}
inline int32_t Ms1ScanInfo::one_based_scan_number() const {
  // @@protoc_insertion_point(field_get:crux_lfq.Ms1ScanInfo.one_based_scan_number)
  return _internal_one_based_scan_number();
}
inline void Ms1ScanInfo::_internal_set_one_based_scan_number(int32_t value) {
  _has_bits_[0] |= 0x00000001u;
  one_based_scan_number_ = value;
}
inline void Ms1ScanInfo::set_one_based_scan_number(int32_t value) {
  _internal_set_one_based_scan_number(value);
  // @@protoc_insertion_point(field_set:crux_lfq.Ms1ScanInfo.one_based_scan_number)
}

// required int32 zero_based_ms1_scan_index = 2;
inline bool Ms1ScanInfo::_internal_has_zero_based_ms1_scan_index() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Ms1ScanInfo::has_zero_based_ms1_scan_index() const {
  return _internal_has_zero_based_ms1_scan_index();
}
inline void Ms1ScanInfo::clear_zero_based_ms1_scan_index() {
  zero_based_ms1_scan_index_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline int32_t Ms1ScanInfo::_internal_zero_based_ms1_scan_index() const {
  return zero_based_ms1_scan_index_;
}
inline int32_t Ms1ScanInfo::zero_based_ms1_scan_index() const {
  // @@protoc_insertion_point(field_get:crux_lfq.Ms1ScanInfo.zero_based_ms1_scan_index)
  return _internal_zero_based_ms1_scan_index();
}
inline void Ms1ScanInfo::_internal_set_zero_based_ms1_scan_index(int32_t value) {
  _has_bits_[0] |= 0x00000002u;
  zero_based_ms1_scan_index_ = value;
}
inline void Ms1ScanInfo::set_zero_based_ms1_scan_index(int32_t value) {
  _internal_set_zero_based_ms1_scan_index(value);
  // @@protoc_insertion_point(field_set:crux_lfq.Ms1ScanInfo.zero_based_ms1_scan_index)
}

// required double retention_time = 3;
inline bool Ms1ScanInfo::_internal_has_retention_time() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Ms1ScanInfo::has_retention_time() const {
  return _internal_has_retention_time();
}
inline void Ms1ScanInfo::clear_retention_time() {
  retention_time_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double Ms1ScanInfo::_internal_retention_time() const {
  return retention_time_;
}
inline double Ms1ScanInfo::retention_time() const {
  // @@protoc_insertion_point(field_get:crux_lfq.Ms1ScanInfo.retention_time)
  return _internal_retention_time();
}
inline void Ms1ScanInfo::_internal_set_retention_time(double value) {
  _has_bits_[0] |= 0x00000004u;
  retention_time_ = value;
}
inline void Ms1ScanInfo::set_retention_time(double value) {
  _internal_set_retention_time(value);
  // @@protoc_insertion_point(field_set:crux_lfq.Ms1ScanInfo.retention_time)
}

// -------------------------------------------------------------------

// IndexedMassSpectralPeak

// required double mz = 1;
inline bool IndexedMassSpectralPeak::_internal_has_mz() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool IndexedMassSpectralPeak::has_mz() const {
  return _internal_has_mz();
}
inline void IndexedMassSpectralPeak::clear_mz() {
  mz_ = 0;
  _has_bits_[0] &= ~0x00000001u;
}
inline double IndexedMassSpectralPeak::_internal_mz() const {
  return mz_;
}
inline double IndexedMassSpectralPeak::mz() const {
  // @@protoc_insertion_point(field_get:crux_lfq.IndexedMassSpectralPeak.mz)
  return _internal_mz();
}
inline void IndexedMassSpectralPeak::_internal_set_mz(double value) {
  _has_bits_[0] |= 0x00000001u;
  mz_ = value;
}
inline void IndexedMassSpectralPeak::set_mz(double value) {
  _internal_set_mz(value);
  // @@protoc_insertion_point(field_set:crux_lfq.IndexedMassSpectralPeak.mz)
}

// required double intensity = 2;
inline bool IndexedMassSpectralPeak::_internal_has_intensity() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool IndexedMassSpectralPeak::has_intensity() const {
  return _internal_has_intensity();
}
inline void IndexedMassSpectralPeak::clear_intensity() {
  intensity_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline double IndexedMassSpectralPeak::_internal_intensity() const {
  return intensity_;
}
inline double IndexedMassSpectralPeak::intensity() const {
  // @@protoc_insertion_point(field_get:crux_lfq.IndexedMassSpectralPeak.intensity)
  return _internal_intensity();
}
inline void IndexedMassSpectralPeak::_internal_set_intensity(double value) {
  _has_bits_[0] |= 0x00000002u;
  intensity_ = value;
}
inline void IndexedMassSpectralPeak::set_intensity(double value) {
  _internal_set_intensity(value);
  // @@protoc_insertion_point(field_set:crux_lfq.IndexedMassSpectralPeak.intensity)
}

// required int32 zero_based_ms1_scan_index = 3;
inline bool IndexedMassSpectralPeak::_internal_has_zero_based_ms1_scan_index() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool IndexedMassSpectralPeak::has_zero_based_ms1_scan_index() const {
  return _internal_has_zero_based_ms1_scan_index();
}
inline void IndexedMassSpectralPeak::clear_zero_based_ms1_scan_index() {
  zero_based_ms1_scan_index_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline int32_t IndexedMassSpectralPeak::_internal_zero_based_ms1_scan_index() const {
  return zero_based_ms1_scan_index_;
}
inline int32_t IndexedMassSpectralPeak::zero_based_ms1_scan_index() const {
  // @@protoc_insertion_point(field_get:crux_lfq.IndexedMassSpectralPeak.zero_based_ms1_scan_index)
  return _internal_zero_based_ms1_scan_index();
}
inline void IndexedMassSpectralPeak::_internal_set_zero_based_ms1_scan_index(int32_t value) {
  _has_bits_[0] |= 0x00000008u;
  zero_based_ms1_scan_index_ = value;
}
inline void IndexedMassSpectralPeak::set_zero_based_ms1_scan_index(int32_t value) {
  _internal_set_zero_based_ms1_scan_index(value);
  // @@protoc_insertion_point(field_set:crux_lfq.IndexedMassSpectralPeak.zero_based_ms1_scan_index)
}

// required double retention_time = 4;
inline bool IndexedMassSpectralPeak::_internal_has_retention_time() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool IndexedMassSpectralPeak::has_retention_time() const {
  return _internal_has_retention_time();
}
inline void IndexedMassSpectralPeak::clear_retention_time() {
  retention_time_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline double IndexedMassSpectralPeak::_internal_retention_time() const {
  return retention_time_;
}
inline double IndexedMassSpectralPeak::retention_time() const {
  // @@protoc_insertion_point(field_get:crux_lfq.IndexedMassSpectralPeak.retention_time)
  return _internal_retention_time();
}
inline void IndexedMassSpectralPeak::_internal_set_retention_time(double value) {
  _has_bits_[0] |= 0x00000004u;
  retention_time_ = value;
}
inline void IndexedMassSpectralPeak::set_retention_time(double value) {
  _internal_set_retention_time(value);
  // @@protoc_insertion_point(field_set:crux_lfq.IndexedMassSpectralPeak.retention_time)
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// InnerMap

// map<int32, .crux_lfq.IndexedMassSpectralPeak> inner_map = 1;
inline int InnerMap::_internal_inner_map_size() const {
  return inner_map_.size();
}
inline int InnerMap::inner_map_size() const {
  return _internal_inner_map_size();
}
inline void InnerMap::clear_inner_map() {
  inner_map_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >&
InnerMap::_internal_inner_map() const {
  return inner_map_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >&
InnerMap::inner_map() const {
  // @@protoc_insertion_point(field_map:crux_lfq.InnerMap.inner_map)
  return _internal_inner_map();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >*
InnerMap::_internal_mutable_inner_map() {
  return inner_map_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::IndexedMassSpectralPeak >*
InnerMap::mutable_inner_map() {
  // @@protoc_insertion_point(field_mutable_map:crux_lfq.InnerMap.inner_map)
  return _internal_mutable_inner_map();
}

// -------------------------------------------------------------------

// Ms1ScanInfoList

// repeated .crux_lfq.Ms1ScanInfo ms1_scan_info = 1;
inline int Ms1ScanInfoList::_internal_ms1_scan_info_size() const {
  return ms1_scan_info_.size();
}
inline int Ms1ScanInfoList::ms1_scan_info_size() const {
  return _internal_ms1_scan_info_size();
}
inline void Ms1ScanInfoList::clear_ms1_scan_info() {
  ms1_scan_info_.Clear();
}
inline ::crux_lfq::Ms1ScanInfo* Ms1ScanInfoList::mutable_ms1_scan_info(int index) {
  // @@protoc_insertion_point(field_mutable:crux_lfq.Ms1ScanInfoList.ms1_scan_info)
  return ms1_scan_info_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crux_lfq::Ms1ScanInfo >*
Ms1ScanInfoList::mutable_ms1_scan_info() {
  // @@protoc_insertion_point(field_mutable_list:crux_lfq.Ms1ScanInfoList.ms1_scan_info)
  return &ms1_scan_info_;
}
inline const ::crux_lfq::Ms1ScanInfo& Ms1ScanInfoList::_internal_ms1_scan_info(int index) const {
  return ms1_scan_info_.Get(index);
}
inline const ::crux_lfq::Ms1ScanInfo& Ms1ScanInfoList::ms1_scan_info(int index) const {
  // @@protoc_insertion_point(field_get:crux_lfq.Ms1ScanInfoList.ms1_scan_info)
  return _internal_ms1_scan_info(index);
}
inline ::crux_lfq::Ms1ScanInfo* Ms1ScanInfoList::_internal_add_ms1_scan_info() {
  return ms1_scan_info_.Add();
}
inline ::crux_lfq::Ms1ScanInfo* Ms1ScanInfoList::add_ms1_scan_info() {
  ::crux_lfq::Ms1ScanInfo* _add = _internal_add_ms1_scan_info();
  // @@protoc_insertion_point(field_add:crux_lfq.Ms1ScanInfoList.ms1_scan_info)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::crux_lfq::Ms1ScanInfo >&
Ms1ScanInfoList::ms1_scan_info() const {
  // @@protoc_insertion_point(field_list:crux_lfq.Ms1ScanInfoList.ms1_scan_info)
  return ms1_scan_info_;
}

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// IndexedSpectralResults

// map<int32, .crux_lfq.InnerMap> indexed_peaks = 1;
inline int IndexedSpectralResults::_internal_indexed_peaks_size() const {
  return indexed_peaks_.size();
}
inline int IndexedSpectralResults::indexed_peaks_size() const {
  return _internal_indexed_peaks_size();
}
inline void IndexedSpectralResults::clear_indexed_peaks() {
  indexed_peaks_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >&
IndexedSpectralResults::_internal_indexed_peaks() const {
  return indexed_peaks_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >&
IndexedSpectralResults::indexed_peaks() const {
  // @@protoc_insertion_point(field_map:crux_lfq.IndexedSpectralResults.indexed_peaks)
  return _internal_indexed_peaks();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >*
IndexedSpectralResults::_internal_mutable_indexed_peaks() {
  return indexed_peaks_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< int32_t, ::crux_lfq::InnerMap >*
IndexedSpectralResults::mutable_indexed_peaks() {
  // @@protoc_insertion_point(field_mutable_map:crux_lfq.IndexedSpectralResults.indexed_peaks)
  return _internal_mutable_indexed_peaks();
}

// map<string, .crux_lfq.Ms1ScanInfoList> ms1_scans = 2;
inline int IndexedSpectralResults::_internal_ms1_scans_size() const {
  return ms1_scans_.size();
}
inline int IndexedSpectralResults::ms1_scans_size() const {
  return _internal_ms1_scans_size();
}
inline void IndexedSpectralResults::clear_ms1_scans() {
  ms1_scans_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >&
IndexedSpectralResults::_internal_ms1_scans() const {
  return ms1_scans_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >&
IndexedSpectralResults::ms1_scans() const {
  // @@protoc_insertion_point(field_map:crux_lfq.IndexedSpectralResults.ms1_scans)
  return _internal_ms1_scans();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >*
IndexedSpectralResults::_internal_mutable_ms1_scans() {
  return ms1_scans_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< std::string, ::crux_lfq::Ms1ScanInfoList >*
IndexedSpectralResults::mutable_ms1_scans() {
  // @@protoc_insertion_point(field_mutable_map:crux_lfq.IndexedSpectralResults.ms1_scans)
  return _internal_mutable_ms1_scans();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace crux_lfq

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_indexed_5fmass_5fspectral_5fpeak_2eproto
