message(LIB="$ENV{LIB}")
message(LIBPATH="$ENV{LIBPATH}")
message(MSBUILD_ARGS=${MSBUILD_ARGS})
message(PROJ_FILE=${PROJ_FILE})
set(ENV{LIBPATH} "$ENV{LIBPATH};${LIBPATH}")
set(ENV{LIB} "$ENV{LIB};${LIBPATH}")
message(LIB="$ENV{LIB}")
message(LIBPATH="$ENV{LIBPATH}")
message(MSBUILD_PLATFORM="${MSBUILD_PLATFORM}")
execute_process(COMMAND msbuild /p:platform=${MSBUILD_PLATFORM} /p:useenv=true ${MSBUILD_ARGS} ${PROJ_FILE})
