name: Build and push container image
on: workflow_dispatch
jobs:
  build_push_container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - name: crux-toolkit
            crux_cmake_args: "-DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/app/"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run docker/setup-qemu-action
        uses: docker/setup-qemu-action@v3
      - name: Run docker/setup-buildx-action
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: List available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Run docker/login-action
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Run docker/metadata-action
        id: metadata_action_id
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ matrix.name }}
          flavor: |
            latest=auto
          tags: |
            type=sha,format=long
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.title=crux-toolkit
            org.opencontainers.image.description=The Crux mass spectrometry analysis toolkit is an open source project that aims to provide users with a cross-platform suite of analysis tools for interpreting protein mass spectrometry data. 
            org.opencontainers.image.url=${{ github.event.repository.html_url }}
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./ghcrDockerfile
          platforms: linux/amd64
          tags: ${{ steps.metadata_action_id.outputs.tags }}
          labels: ${{ steps.metadata_action_id.outputs.labels }}
          build-args: |
           "crux_cmake_args=${{ matrix.crux_cmake_args }}"
