name: Check release notes

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cpplint

      - name: Check that release notes have been updated
        shell: bash
        run: |
          content=$(git diff origin/master -- doc/user/release-notes.html)
          if [[ ! $content ]]; then
              echo "Please update the release notes (doc/user/release-notes.html)."
              exit 1
          fi

      - name: Lint the proposed changes using cpplint
        shell: bash
        run: |
          cd test/lint && python lint.py -d
