name: Build and Test Crux on Ubuntu

on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  CRUX_VERSION: 4.3.2

jobs:
  build:
    name: Setup and Build Crux
    runs-on: 'ubuntu-22.04'

    steps:
      - name: checkout-repository    
        uses: actions/checkout@v6
 
      - name: Get short git sha
        shell: bash
        run: |
          echo "git_short_sha=`git rev-parse --short HEAD`"  >> $GITHUB_ENV
          
      - name: Configure Crux build
        shell: bash
        run: |
              cmake -E make_directory "${{runner.workspace}}/build"
              cd "${{runner.workspace}}/build"
              echo Configuring in $(pwd)
              cmake "${{github.workspace}}" -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build Crux
        shell: bash
        run: |
             cd "${{runner.workspace}}/build"
             echo Building in $(pwd)
             cmake --build . --config $BUILD_TYPE 

      - name: Build package
        shell: bash
        run: |
             cd "${{runner.workspace}}/build"
             cmake --build . --config $BUILD_TYPE --target package

      - name: Archive package
        uses: actions/upload-artifact@v6
        with:
          name: crux-${{env.CRUX_VERSION}}.${{env.git_short_sha}}.ubuntu.22.04
          path:  ${{runner.workspace}}/build/crux-${{env.CRUX_VERSION}}.Linux.x86_64.zip

      - name: Build source package
        shell: bash
        run: |
             cd "${{runner.workspace}}/build"
             cmake --build . --config $BUILD_TYPE --target package_source

      - name: Archive source package
        uses: actions/upload-artifact@v6
        with:
          name: crux-${{env.CRUX_VERSION}}.${{env.git_short_sha}}.Source
          path: ${{runner.workspace}}/build/crux-${{env.CRUX_VERSION}}.Source.tar.gz

  test:
    name: Test Crux with smoke-tests
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-repository    
        uses: actions/checkout@v6
 
      - name: setup-python
        uses: actions/setup-python@v6
        with: 
            python-version: 3.x
      
      - name: download-and-extract-package
        shell: bash
        run: |
             cd "${{runner.workspace}}/build"
             echo Downloading package from build job
             gh run download --name "crux-${{env.CRUX_VERSION}}.${{env.git_short_sha}}.ubuntu.22.04.zip" --dir .
             unzip "crux-${{env.CRUX_VERSION}}.${{env.git_short_sha}}.ubuntu.22.04.zip" -d .
 
      - name: setup-for-tests
        shell: bash
        run: |
              python -m pip install numpy
              python -m pip install pandas
              sudo apt-get install ruby
              sudo apt-get install cucumber
              sudo gem install rspec

      - name: Test
        continue-on-error: true
        shell: bash
        run: |
             cd ${{runner.workspace}}/build/test
             rm -rf smoke-tests
             cp -r /home/runner/work/crux-toolkit/crux-toolkit/test/smoke-tests .
             cd smoke-tests
             cucumber -v -f html -o smoke-tests.html \
               && echo "cucumber_exit_code=$?"  >> $GITHUB_ENV \
               || echo "cucumber_exit_code=$?"  >> $GITHUB_ENV \
               && echo $cucumber_exit_code

      - name: Archive smoke test results
        uses: actions/upload-artifact@v6
        with:
          name: smoke.html
          path: ${{runner.workspace}}/build/test/smoke-tests/smoke-tests.html
          
      - name: Let the workflow fail if the test suite failed
        shell: bash
        run: |
          bash -c 'exit "${{env.cucumber_exit_code}}"'
